// web/src/lib/components/Badge.svelte
<script lang="ts">
  import type { Snippet } from 'svelte';

  let {
    children,
    tone = 'neutral'
  }: { children: Snippet; tone?: 'neutral' | 'success' | 'warning' | 'accent' } = $props();
</script>

<span class="badge {tone}">{@render children()}</span>

<style>
  .badge {
    display: inline-flex;
    min-height: 1.55rem;
    align-items: center;
    padding: 0.2rem 0.5rem;
    border: 1px solid var(--line);
    border-radius: 999px;
    background: var(--surface-muted);
    color: var(--ink-secondary);
    font-size: 0.67rem;
    font-weight: 720;
    letter-spacing: 0.05em;
    text-transform: uppercase;
  }

  .success {
    border-color: color-mix(in srgb, var(--success) 28%, transparent);
    background: color-mix(in srgb, var(--success) 10%, transparent);
    color: var(--success);
  }

  .warning {
    border-color: color-mix(in srgb, var(--warning) 28%, transparent);
    background: color-mix(in srgb, var(--warning) 10%, transparent);
    color: var(--warning);
  }

  .accent {
    border-color: color-mix(in srgb, var(--accent) 32%, transparent);
    background: var(--accent-soft);
    color: var(--accent);
  }
</style>

// web/src/components/ui/badge.tsx
import type { HTMLAttributes } from 'react';

import { cx, variantClass } from './styles';

const badgeTones = {
  neutral: 'border-border-subtle bg-surface-sunken text-text-muted',
  accent: 'border-accent-border bg-accent-subtle text-accent-text',
  success: 'border-success-border bg-success-subtle text-success-text',
  warning: 'border-warning-border bg-warning-subtle text-warning-text',
  danger: 'border-danger-border bg-danger-subtle text-danger-text',
  info: 'border-info-border bg-info-subtle text-info-text'
} as const;

export type BadgeTone = keyof typeof badgeTones;

export interface BadgeProps extends HTMLAttributes<HTMLSpanElement> {
  tone?: BadgeTone;
}

export function Badge({ className, tone = 'neutral', ...props }: BadgeProps) {
  return (
    <span
      {...props}
      className={cx(
        'inline-flex w-fit items-center gap-1 rounded-sm border px-2 py-1',
        'text-xs font-medium',
        variantClass(badgeTones, tone),
        className
      )}
    />
  );
}
