// web/src/components/ui/button.tsx
'use client';

import { LoaderCircle } from 'lucide-react';
import {
  Button as ReactAriaButton,
  type ButtonProps as ReactAriaButtonProps
} from 'react-aria-components';

import { cx, focusRing, variantClass } from './styles';

const buttonTones = {
  primary: cx(
    'border-accent bg-accent text-text-on-accent',
    'hover:bg-accent-hover pressed:bg-accent-hover'
  ),
  secondary: cx(
    'border-border-subtle bg-surface-raised text-text',
    'hover:border-border hover:bg-surface-hover',
    'pressed:bg-surface-active'
  ),
  quiet: cx(
    'border-transparent bg-transparent text-text-muted shadow-none',
    'hover:bg-surface-hover hover:text-text',
    'pressed:bg-surface-active'
  ),
  danger: cx(
    'border-danger bg-danger text-text-on-accent',
    'hover:bg-danger-hover pressed:bg-danger-hover'
  )
} as const;

const buttonSizes = {
  small: 'gap-1 px-3 py-1 text-sm',
  medium: 'gap-2 px-4 py-2 text-sm',
  large: 'gap-2 px-6 py-3 text-base',
  icon: 'p-2'
} as const;

export type ButtonTone = keyof typeof buttonTones;
export type ButtonSize = keyof typeof buttonSizes;

export interface ButtonProps extends ReactAriaButtonProps {
  isLoading?: boolean;
  size?: ButtonSize;
  tone?: ButtonTone;
}

export function Button({
  children,
  className,
  isDisabled,
  isLoading = false,
  size = 'medium',
  tone = 'primary',
  ...props
}: ButtonProps) {
  return (
    <ReactAriaButton
      {...props}
      className={cx(
        'inline-flex items-center justify-center rounded-md border font-medium',
        'outline-none transition-colors duration-fast ease-out-quart',
        'disabled:cursor-not-allowed disabled:border-border-subtle',
        'disabled:bg-surface-active disabled:text-text-subtle',
        focusRing,
        variantClass(buttonTones, tone),
        variantClass(buttonSizes, size),
        typeof className === 'string' ? className : undefined
      )}
      aria-busy={isLoading || undefined}
      isDisabled={isDisabled || isLoading}
    >
      {(values) => {
        const resolvedChildren = typeof children === 'function' ? children(values) : children;

        return isLoading ? (
          <>
            <LoaderCircle aria-hidden className="size-4 animate-spin" />
            <span>{resolvedChildren}</span>
          </>
        ) : (
          resolvedChildren
        );
      }}
    </ReactAriaButton>
  );
}

// web/src/lib/components/Button.svelte
<script lang="ts">
  import type { Snippet } from 'svelte';

  let {
    children,
    variant = 'primary',
    type = 'button',
    disabled = false,
    loading = false,
    onclick,
    ariaLabel
  }: {
    children: Snippet;
    variant?: 'primary' | 'secondary' | 'quiet' | 'danger';
    type?: 'button' | 'submit' | 'reset';
    disabled?: boolean;
    loading?: boolean;
    onclick?: (event: MouseEvent) => void;
    ariaLabel?: string;
  } = $props();
</script>

<button
  class="button {variant}"
  {type}
  disabled={disabled || loading}
  aria-busy={loading}
  aria-label={ariaLabel}
  {onclick}
>
  {#if loading}
    <span class="spinner" aria-hidden="true"></span>
  {/if}
  <span class:visually-muted={loading}>{@render children()}</span>
</button>

<style>
  .button {
    position: relative;
    display: inline-flex;
    min-height: 2.65rem;
    align-items: center;
    justify-content: center;
    gap: 0.5rem;
    padding: 0.62rem 1rem;
    border: 1px solid transparent;
    border-radius: var(--radius-sm);
    cursor: pointer;
    font-size: 0.88rem;
    font-weight: 680;
    letter-spacing: -0.01em;
    transition:
      transform var(--duration-fast),
      background var(--duration-fast),
      border-color var(--duration-fast),
      opacity var(--duration-fast);
  }

  .button:hover:not(:disabled) {
    transform: translateY(-1px);
  }

  .button:active:not(:disabled) {
    transform: translateY(0);
  }

  .primary {
    background: var(--accent);
    color: var(--on-accent);
  }

  .primary:hover:not(:disabled) {
    background: var(--accent-strong);
  }

  .secondary {
    border-color: var(--line-strong);
    background: var(--surface-raised);
    color: var(--ink);
  }

  .secondary:hover:not(:disabled),
  .quiet:hover:not(:disabled) {
    background: var(--surface-muted);
  }

  .quiet {
    background: transparent;
    color: var(--ink-secondary);
  }

  .danger {
    border-color: color-mix(in srgb, var(--danger) 35%, transparent);
    background: color-mix(in srgb, var(--danger) 12%, transparent);
    color: var(--danger);
  }

  .button:disabled {
    cursor: not-allowed;
    opacity: 0.5;
  }

  .spinner {
    position: absolute;
    width: 1rem;
    height: 1rem;
    border: 2px solid currentColor;
    border-right-color: transparent;
    border-radius: 999px;
    animation: spin 700ms linear infinite;
  }

  .visually-muted {
    opacity: 0;
  }

  @keyframes spin {
    to {
      transform: rotate(360deg);
    }
  }

  @media (prefers-reduced-motion: reduce) {
    .spinner {
      animation-duration: 1.5s;
    }
  }
</style>
